package soms

type KDDCup struct{
    Duration int
    Protocol_type string
    Service string
    Flag string
    Src_bytes int
    Dst_bytes int
    Land string
    Wrong_fragment int
    Urgent int
    Hot int
    Num_failed_logins int
    Logged_in string
    Num_compromised int
    Root_shell int
    Su_attempted int 
    Num_root int
    Num_file_creations int
    Num_shells int
    Num_access_files int
    Num_outbound_cmds int
    Is_host_login string
    Is_guest_login string
    Count int
    Srv_count int
    Serror_rate int
    Srv_serror_rate int
    Rerror_rate int
    Srv_rerror_rate int
    Same_srv_rate int
    Diff_srv_rate int
    Srv_diff_host_rate int
    Dst_host_count int
    Dst_host_srv_count int
    Dst_host_same_srv_rate int
    Dst_host_diff_srv_rate int
    Dst_host_same_src_port_rate int
    Dst_host_srv_diff_host_rate int
    Dst_host_serror_rate int
    Dst_host_srv_serror_rate int
    Dst_host_rerror_rate int
    Dst_host_srv_rerror_rate int
    Attack string
}

package soms

type KDDNormal struct{
    Duration int
    Protocol_type string
    Service string
    Flag string
    Src_bytes int
    Dst_bytes int
    Land string
    Wrong_fragment int
    Urgent int
    Hot int
    Num_failed_logins int
    Logged_in string
    Num_compromised int
    Root_shell int
    Su_attempted int 
    Num_root int
    Num_file_creations int
    Num_shells int
    Num_access_files int
    Num_outbound_cmds int
    Is_host_login string
    Is_guest_login string
    Count int
    Srv_count int
    Serror_rate int
    Srv_serror_rate int
    Rerror_rate int
    Srv_rerror_rate int
    Same_srv_rate int
    Diff_srv_rate int
    Srv_diff_host_rate int
    Dst_host_count int
    Dst_host_srv_count int
    Dst_host_same_srv_rate int
    Dst_host_diff_srv_rate int
    Dst_host_same_src_port_rate int
    Dst_host_srv_diff_host_rate int
    Dst_host_serror_rate int
    Dst_host_srv_serror_rate int
    Dst_host_rerror_rate int
    Dst_host_srv_rerror_rate int
    Attack string
}