language: go
notificaitons:
  email:
    recipients: rodrigo-mendonca@outlook.com.br
    on_success: change
    on_failure: always
install:
- go get gopkg.in/mgo.v2
- go get gopkg.in/mgo.v2/bson
- go get github.com/rodrigo-mendonca/TCCSenac/neuron
- go get github.com/rodrigo-mendonca/TCCSenac/kohonen
- go get github.com/rodrigo-mendonca/TCCSenac/somfunctions

script:
- go test github.com/rodrigo-mendonca/TCCSenac/foofinder